### PR TITLE
Added kuga, which is a European escape

### PR DESCRIPTION
**Pull request by consp**
This is meant as a suggested contribution, if you disagree with the method chosen feel free to edit it. I'm not a java developer so maybe I screwed up somewhere (it works with my vehicle, cannot test on others).

My kuga was detected as "other" and it works perfectly after modifying the it to match a PHEV instead of electric as I was missing the fuel gauge. The European Kuga is the same car as the American Escape, there is no difference except some badges and engine options .

The modifications are as follows:
* excluded kuga from the mache select since it thinks all Europeans drive full electric
* Added kuga vin selection for what I know: Model number is M, Type is H or F (for Hybrid or Fueled I guess?), years are KLMN (2019-2022): e.g. mine is a MHL.

Issues:
* As far as I know there is now way to determine the PHEV from the FHEV from the VIN alone.
* I have no AWD VIN, maybe those have different model numbers.

### CODE REVIEW

**Comment by khpylon** [comment]
Thanks for the code.  I'm going to rework it a little, but it would be helpful to know what digits 4-11 of your VIN.  I've had trouble finding good info on European VINs and almost nothing on Ford VINs after 2009.  What I have found this morning are mostly vehicles starting with either WF0FXXWPM or WF0AXXWPM, and digit 11 is the year (as you found).  But the vehicle descriptor section should be digits 4-9.  I don't think there shouldn't be any info about the engine type in the other digits.

**Comment by consp** [comment]
I'm pretty sure the first six ones are predefined by origin and type or something like that, WF0 is Ford of Europe (indicated as FoE in many Ford texts). I'll send you the VINs I have of kuga's from Europe (used them for APIM settings purposes). I'm not going to send VINs in plain public though as it can be abused, is there a way to contact you otherwise?

I'm also pretty sure the vehicle descriptor is only valid for the US, at least for the first few digits.

As far as I know:
WF0 -- manufacturing plant, all say the same (Since WF0 is Ford of Europe)
FXX -- the first digit is different for other car's, my old fiesta had CXX for example (could indicate vehicle model but all have xx)
WPM -- All the same for all models I can find of the Kuga's
H or F  -- All (P/F)HEV have H, all Diesels and Gasoline have F. I have not found an exception tough my sample size is limited
[single character year]
[single character unknown, probably preamble for serial or extended date code]
[serial]

I know for certain the 9th digit is the type and the 10th is a bit less certain, though looking at all the models I could get the VINs from I'm positive it defines the fuel type for the Kuga's but it could be type dependent.

First time I read wikipedia about it:
[4-9] Indication of "the general characteristics of the vehicle"
[10-17] Indication that provides "clear identification of a particular vehicle"
So it could  be anything ...

**Comment by khpylon** [comment]
I'm interpreting the VIN based on these sources:
- https://en.wikipedia.org/wiki/Vehicle_identification_number
- https://www.carfax.eu/blog/vehicle-identification-number-vin
- https://www.nsai.ie/certification/automotive/transport-schemes/world-manufacturer-identifier

I just don't have a lot of info what Ford put in the Vehicle Descriptor.  I did find this for older VINs, which somewhat works still:
- Position 4: Body Type
- Position 5-6: always XX
- Position 7: Line
- Position 8: Assembly Plant
- Position 9: Model
- Position 10: duplicate of position 4
- Position 11: Year

but I've found a few VINs with position 10 different from position 4, so you are probably right that it's something to do with the engine.  I think you're also right that **WPM** is unique for the Kuga, although it could literally mean they're all made on the same assembly plant's line.  I've found a bunch of Pumas and they're all **ERK**.

**Comment by khpylon** [comment]
I know it's gotta be late there, but I used the info we've discussed and brewed up a version you can test.  I'm assuming you're not on the Mach-E/F-150/Bronco forums, so if you want to send me an e-mail (khpylon@gmail.com) I'll send you a link to try.

**Comment by khpylon** [comment]
Actually since you've obviously built it yourself, I just pushed my updates in Utils.java so you can pull and build yourself.

**Comment by consp** [comment]
The changes in the master branch seem to work.

I would add this as well as it would change the image to the escape image (unless I screwed up the merge somewhere and this is just the result of me using git wrong):
```
diff --git a/app/src/main/java/com/example/khughes/machewidget/Utils.java b/app/src/main/java/com/example/khughes/machewidget/Utils.java
index 438abe8..8357e65 100644
--- a/app/src/main/java/com/example/khughes/machewidget/Utils.java
+++ b/app/src/main/java/com/example/khughes/machewidget/Utils.java
@@ -702,7 +702,7 @@ public class Utils {
                 return broncobase4x4Drawables;
             } else if (isExplorer(VIN)) {
                 return explorerSTDrawables;
-            } else if (isEscape(VIN)) {
+            } else if (isEscape(VIN) || isKuga(VIN)) {
                 return escapeDrawables;
             } else if (isEdge(VIN)) {
                 return edgeDrawables;
```

**Comment by consp** [comment]
I also noticed if you select the escape image the locked image disappears in the 1x5 widget if you select "color" mode, it is shown in wireframe.

**Comment by khpylon** [comment]
> The changes in the master branch seem to work.
> 
> I would add this as well as it would change the image to the escape image (unless I screwed up the merge somewhere and this is just the result of me using git wrong):
> 
> ```
> diff --git a/app/src/main/java/com/example/khughes/machewidget/Utils.java b/app/src/main/java/com/example/khughes/machewidget/Utils.java
> index 438abe8..8357e65 100644
> --- a/app/src/main/java/com/example/khughes/machewidget/Utils.java
> +++ b/app/src/main/java/com/example/khughes/machewidget/Utils.java
> @@ -702,7 +702,7 @@ public class Utils {
>                  return broncobase4x4Drawables;
>              } else if (isExplorer(VIN)) {
>                  return explorerSTDrawables;
> -            } else if (isEscape(VIN)) {
> +            } else if (isEscape(VIN) || isKuga(VIN)) {
>                  return escapeDrawables;
>              } else if (isEdge(VIN)) {
>                  return edgeDrawables;
> ```

Good catch.

**Comment by khpylon** [comment]
> I also noticed if you select the escape image the locked image disappears in the 1x5 widget if you select "color" mode, it is shown in wireframe.

Ok, I'll check on that.

**Comment by khpylon** [comment]
> I also noticed if you select the escape image the locked image disappears in the 1x5 widget if you select "color" mode, it is shown in wireframe.

Can you post screenshots?  I'm guessing you have the PHEV?

**Comment by khpylon** [comment]
> > I also noticed if you select the escape image the locked image disappears in the 1x5 widget if you select "color" mode, it is shown in wireframe.
> 
> Can you post screenshots? I'm guessing you have the PHEV?

In res/layout/widget_1x5.xml, try moving the "@+id/lock_electric" ImageView to after the "@+id/wireframe" ImageView.

**Comment by consp** [comment]
Normal mode (with Kuga=Escape image modification bottom, normal in-store app top)
Screenshot_20220720-213720

Color mode (with Kuga=Escape image modification bottom, normal in-store app top)
Screenshot_20220720-213658

Changing the order helped:

Screenshot_20220720-214515

**Comment by consp** [comment]
Changes:

```
diff --git a/app/src/main/res/layout/widget_1x5.xml b/app/src/main/res/layout/widget_1x5.xml
index 026b811..a1077f9 100644
--- a/app/src/main/res/layout/widget_1x5.xml
+++ b/app/src/main/res/layout/widget_1x5.xml
@@ -172,17 +172,6 @@

     </LinearLayout>

-    <ImageView
-        android:id="@+id/lock_electric"
-        android:layout_width="24dp"
-        android:layout_height="100dp"
-        android:layout_alignParentTop="true"
-        android:layout_toEndOf="@id/icons"
-        android:layout_marginLeft="75dp"
-        android:src="@drawable/locked_icon_green"
-        android:layout_weight="1"
-        android:visibility="visible"/>
-
     <!--
     <ImageView
         android:id="@+id/hood"
@@ -346,4 +335,15 @@
         android:layout_alignBottom="@id/wireframe"
         android:src="@drawable/refresh_icon" />

-</RelativeLayout>
\ No newline at end of file
+    <ImageView
+        android:id="@+id/lock_electric"
+        android:layout_width="24dp"
+        android:layout_height="100dp"
+        android:layout_alignParentTop="true"
+        android:layout_toEndOf="@id/icons"
+        android:layout_marginLeft="75dp"
+        android:src="@drawable/locked_icon_green"
+        android:layout_weight="1"
+        android:visibility="visible"/>
+
+</RelativeLayout>
```

Put in branch https://github.com/consp/MachEWidget/tree/kuga-as-escape-and-lock-icon

**Pull request closed without merging**
